os:
- linux
language: generic
sudo: required
dist: trusty
services:
- docker
install:
- eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install 3.0 ; fi
- swiftenv global 3.0
- swift build
- swift test
- docker build -t therickys93/emergencyserver .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker
  push therickys93/emergencyserver; fi
deploy:
  provider: heroku
  buildpack: https://github.com/vapor/heroku-buildpack.git
  app: emergency-server
  strategy: git
  api_key:
    secure: Tko9xb5k0HNoQTBB594dpdO56WMZiN8a/szYckT9cmlqUAW5t3xBoOpdZnTamtkV/P5AhaVhquKqLb8TYtFEM6Gf8V0L6HFQ2WELNtYeBtn/1UYFjjNXlW6KLqVBsdC346MNFa97NPdplG84EdTX1peiy3ZdMeJLKuwVJOiSaH6oRlnN/HFqmj1kkltW+96shcfWbjgzgYIGI220JoXsn7YwantvOYi+in7bn6RGiL2CSFoT25TJ1w/g57ViT8uPjHZq7S11EUHFMGQhZzqq44dnkv2/UaERQvh5ZMoMLmvhr9Q6923Me3xhb6e9XpjvG4+8N/9/jdhoXF4XZpwEDTD4P5QdwEyejdYi2ZV3WAkKvIDkd9bByjTh4gmH0L1QN/rxs+Brb7sa0dZL6/3khqh/6BzXxAXAH1okIIvVAOudO2F4OA6X8RDPUJRTf1C84koqR7Fe14e3kgmMmTbfgAuvxdexALVCKon2LFfoq3lwFpl+oiM/c29OPNH7VqYY/JWUZq8pikLZXVKw2U4AwjlveAKGym8NdknXTMbLihErmg2PxKddAY501K/rFfU1w4S23Hgo7W6caMrMEcVT+sURWslgTzhdQuParVH9Wq26uQy9HMFyDdryi5xcqb3dsK0Uj9iysLtwOncsUWVuP5nsAHyNdC2CApmP289V930=
