image: therickys93/ubuntu14swiftenv

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y libmysqlclient18 libmysqlclient-dev &&
          - swiftenv install 3.0
          - swiftenv global 3.0
          - swift build -Xswiftc -I/usr/local/mysql/include -Xlinker -L/usr/local/mysql/lib -Xswiftc -DNOJSON
          - swift test -Xswiftc -I/usr/local/mysql/include -Xlinker -L/usr/local/mysql/lib -Xswiftc -DNOJSON